#ifndef XDKJ_DATAHANDLER_GLOBAL_H
#define XDKJ_DATAHANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USE_STATIC_LIB)
#define DATAHANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#if defined(DATAHANDLER_LIBRARY)
#  define DATAHANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAHANDLERSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif

#endif // XDKJ_DATAHANDLER_GLOBAL_H
