#ifndef XDKJ_MESSAGEHANDLER_GLOBAL_H
#define XDKJ_MESSAGEHANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USE_STATIC_LIB)
#define MESSAGEHANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#if defined(MESSAGEHANDLER_LIBRARY)
#  define MESSAGEHANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MESSAGEHANDLERSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif

#endif // XDKJ_MESSAGEHANDLER_GLOBAL_H
